# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd35dd949fad54bebfc086128fbdffb4217260c0c1b93164075a9b43603f8d8b86b620c9e62cf4ea7f764a606255feba95fb6eda66c4432f757deb53d2663b6

test:
  secret_key_base: 583177e104417742ab4a67621364a23ed60709bff2e86c93e5ca49d806f5b508a715990a9d6d0a4157b335ab3fd07c0753fb6180cb5ee87f353262304b3a5296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
